# Generated by Django 5.0 on 2023-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADM', 'Admin'), ('AUT', 'Author'), ('USR', 'User')], default='USR', max_length=3),
        ),
    ]
