# Generated by Django 5.0 on 2023-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/users/default.png', upload_to='images/users', verbose_name='Image'),
        ),
    ]
