# Generated by Django 5.0 on 2023-12-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_created_at_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUP', 'Superuser'), ('CBT', 'Contributor'), ('RDR', 'Reader')], default='RDR', max_length=3),
        ),
    ]
