# Generated by Django 5.0 on 2023-12-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/users/default.png', upload_to='images/users', verbose_name='Image'),
        ),
    ]
