# Generated by Django 5.0 on 2023-12-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='slug',
        ),
    ]
