# Generated by Django 5.0 on 2023-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_commentreply_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='slug',
        ),
    ]
